### ISSUE TITLE
Buildcraft - Missing Pipe graphics

### ISSUE THREAD

**Issue by SakuraIsayeki** [Rexacraft/RC4-Client#6]
Buildcraft pipes are missing graphics. Items within the pipes are visible, but the pipe contour is invisible.
Pipes otherwise work as intended.

![image](https://user-images.githubusercontent.com/4705518/82697927-220d8800-9c6a-11ea-9a4a-0b4aef3f2d12.png)

Player @JustinLuca however claims to see the pipes normally.

**Comment by SakuraIsayeki** [comment]
Issue linked to addition of Mod "Buildcraft" on DEV_5 release : ae1485e

**Comment by SakuraIsayeki** [comment]
Following up, Buildcraft's Quarry Frames are also invisible, but working as intended. 
![image](https://user-images.githubusercontent.com/4705518/82698611-5f264a00-9c6b-11ea-8fa0-7848e83840d9.png)

**Comment by JustinLuca** [comment]
For me everything is normal. I can see my pipes and the quarry.

![image](https://user-images.githubusercontent.com/65736038/82698935-073c1300-9c6c-11ea-8036-ea0e584bfeae.png)

**Comment by SakuraIsayeki** [comment]
Issue seems to be linked to Optifine, according to an issue posted on Buildcraft repo : https://github.com/BuildCraft/BuildCraft/issues/3940

**Comment by SakuraIsayeki** [comment]
Pipes finally display after disabling Optifine's Anisotropic Filtering.
Issue closed.
